### ISSUE TITLE
温馨提示🤪

### ISSUE THREAD

**Issue by Purple-CSGO** [hx-w/csgowiki-docs#1]
vercel被墙了，国内访问不了，可以用Cloudflare的DNS让网站走CF的代理，效果还不错

**Comment by hx-w** [comment]
我试试，本来想用腾讯云搞，但是按量收费怕被宰了。
vercel好像也没完全被墙，我vercel上只有博客被墙了，其他的服务虽然慢还是能用，就有点离谱。
